version: '3'
services:

  server01:
    build: ./
    container_name: server01
    image: micseres/micro-services-hub
    environment:
     - APP_ENV=prod
     - APP_ENV=dev
     - LOG_DIR=./var/logs/server.log
     - LOG_LEVEL=100
     - SOCKET_FRONT_TYPE=tcp
     - SOCKET_FRONT_HOST=0.0.0.0
     - SOCKET_FRONT_PORT=9501
     - SOCKET_BACK_TYPE=tcp
     - SOCKET_BACK_HOST=0.0.0.0
     - SOCKET_BACK_PORT=9502
     - SOCKET_SYSTEM_TYPE=tcp
     - SOCKET_SYSTEM_HOST=0.0.0.0
     - SOCKET_SYSTEM_PORT=9503
    networks:
      hub:
        ipv4_address: 10.5.0.101
    volumes:
      - ./:/app

  client1:
    build: ./test/client
    container_name: client1
    image: micseres/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.102
    depends_on:
      - server01
    environment:
     - NAME=client1
    volumes:
      - ./test/client:/app

  client2:
    build: ./test/client
    container_name: client2
    image: micseres/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.103
    depends_on:
      - server01
    environment:
     - NAME=client2
    volumes:
      - ./test/client:/app

  client3:
    build: ./test/client
    container_name: client3
    image: micseres/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.104
    environment:
     - NAME=client3
    depends_on:
      - server01
    volumes:
      - ./test/client:/app

  client4:
    build: ./test/client
    container_name: client4
    image: micseres/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.105
    depends_on:
      - server01
    environment:
     - NAME=client4
    volumes:
      - ./test/client:/app

  client5:
    build: ./test/client
    container_name: client5
    image: micseres/micro-services-client
    networks:
      hub:
        ipv4_address: 10.5.0.106
    depends_on:
      - server01
    environment:
     - NAME=client5
    volumes:
      - ./test/client:/app

  service1:
    build: ./test/microserver
    container_name: service1
    image: micseres/micro-services-service
    networks:
      hub:
        ipv4_address: 10.5.0.107
    depends_on:
      - server01
    environment:
      - NAME=service1
    volumes:
      - ./test/microserver:/app

  service2:
    build: ./test/microserver
    container_name: service2
    image: micseres/micro-services-service
    networks:
      hub:
        ipv4_address: 10.5.0.108
    depends_on:
      - server01
    environment:
      - NAME=service2
    volumes:
    - ./test/microserver:/app

  service3:
    build: ./test/microserver
    container_name: service3
    image: micseres/micro-services-service
    networks:
      hub:
        ipv4_address: 10.5.0.109
    depends_on:
      - server01
    environment:
      - NAME=service3
    volumes:
    - ./test/microserver:/app

networks:
  hub:
    external: true
#docker network create --gateway 10.5.0.1 --subnet 10.5.0.0/24 hub
